/**
 * Single source of truth for the TuranEliteLimo fleet.
 * Used by both Fleet (homepage showcase) and FleetPicker (inside BookingForm).
 * Keep `name` in sync with backend VEHICLE_TYPES.
 */
export const FLEET = [
  {
    name: "Executive Sedan",
    model: "Cadillac XTS · Lincoln Continental · Mercedes E-Class · BMW 5 Series",
    pax: "1–3",
    bags: "3",
    note: "The standard for daily executive transport. Discreet, smooth, on time.",
    img: "/fleet/executive-sedan.jpg",
  },
  {
    name: "First Class",
    model: "Mercedes S-Class · BMW 7 Series · Audi A8",
    pax: "1–3",
    bags: "3",
    note: "First-class flagship. Hush-quiet cabin, executive rear seating.",
    img: "/fleet/first-class.jpg",
  },
  {
    name: "Luxury SUV",
    model: "Cadillac Escalade · GMC Yukon Denali · Lincoln Navigator",
    pax: "1–6",
    bags: "6",
    note: "Captain's chairs, cavernous trunk, redefined comfort.",
    img: "/fleet/luxury-suv.jpg",
  },
  {
    name: "Stretch Limousine",
    model: "Hummer Stretch · Chrysler 300 Stretch",
    pax: "8–14",
    bags: "4",
    callOnly: true,
    note: "Mood lighting, premium bar, the showstopper for weddings & nightlife.",
    img: "/fleet/stretch-limo.jpg",
  },
  {
    name: "Sprinter Van",
    model: "Mercedes Sprinter · Passenger Coach",
    pax: "10–14",
    bags: "14",
    callOnly: true,
    note: "Standard group travel. Cloth or leather seating, AC, ample luggage. Best value for airport runs and team transport.",
    img: "/fleet/sprinter.jpg",
  },
  {
    name: "Executive Sprinter",
    model: "Mercedes Sprinter Executive · Captain's Chairs",
    pax: "8–12",
    bags: "12",
    callOnly: true,
    note: "Captain's chairs, leather, wood trim, partition. Corporate roadshows, executive groups, premium airport transfers.",
    img: "/fleet/sprinter.jpg",
  },
  {
    name: "Jet Sprinter",
    model: "Mercedes Jet Sprinter · First-Class Limo Van",
    pax: "8–10",
    bags: "10",
    callOnly: true,
    note: "First-class recliners, mood lighting, premium bar, club sound. Weddings, prom, special events, VIP airport.",
    img: "/fleet/sprinter.jpg",
  },
  {
    name: "Party Bus",
    model: "14–30 Passenger Limo Coach",
    pax: "14–30",
    bags: "8",
    callOnly: true,
    note: "Built for celebrations. LED lighting, premium sound, dance floor, full bar.",
    img: "/fleet/party-bus.jpg",
  },
  {
    name: "Mini Coach",
    model: "24–35 Passenger Mid-Size Coach",
    pax: "24–35",
    bags: "20",
    callOnly: true,
    note: "The mid-size charter. High-back reclining seats, AC, luggage bay. Wedding guest shuttles, sports teams, mid-size corporate groups.",
    img: "/fleet/mini-coach.jpg",
  },
  {
    name: "Motor Coach",
    model: "40–56 Passenger Charter Bus",
    pax: "40–56",
    bags: "56",
    callOnly: true,
    note: "Full-size touring coach. Reclining seats, restroom onboard, PA system, luggage bay, WiFi option. Corporate roadshows, large weddings, tours, sports teams.",
    img: "/fleet/motor-coach.jpg",
  },
];
